FROM archlinux:latest

ENV DEBIAN_FRONTEND noninteractive

RUN pacman -Syyu --noconfirm ruby fontconfig freetype2 libjpeg libpng libxext libxrender openssl-1.1

CMD /root/wkhtmltopdf_binary_gem/bin/wkhtmltopdf --version
